[tool.mypy]
python_version = 3.9
allow_redefinition = false
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true

[email.gmail]
path_credential_json = "./credentials.json"
path_token_json = "./token.json"

[dask]
use_processes = false
dashboard_address = ":8787"
scheduler_port = 8786
num_workers = 1
threads_per_worker = 1
memory_limit = 0

[logs]
dir_name = "logs"
file_name = "impressions_datasets.log"
formatter = "%(process)d|%(asctime)s|%(levelname)s|%(module)s|%(funcName)s|%(lineno)d|%(message)s"

[tool.poetry]
name = "impressions_datasets"
version = "1.0.0"
description = ""
authors = [
    "Anonymous <Anonymous>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
typed-argument-parser = "^1.7.1"
recsys-framework-public = { path = "../RecSysFramework_public/", develop = true }  # Use this when publishing the repo.
# recsys-framework-public = { git = "https://github.com/fernandobperezm/RecSysFramework_public.git", rev = "5dbd3344b21750efee17250d6788fb6de8f850e1" }
recsys-framework-extensions = { path = "../recsys-framework-extensions/", develop = true, extras = ["email-gmail"] }  # Use this when publishing the repo.
plotly = "^5.5.0"
datashader = "^0.13.0"
kaleido = "=0.2.1"
jupyter = "^1.0.0"
jupyterlab = "^3.3.0"
cattrs = "^22.1.0"

[tool.poetry.dev-dependencies]
mypy = "^0.950"
black = "^21.11b1"
pytest = "^6.2.4"
memory-profiler = "^0.58.0"
types-toml = "^0.10.0"
pylint = "^2.12.2"
Faker = "^13.3.4"
mock = "^4.0.3"
types-mock = "^4.0.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
